### PR TITLE
Update links color

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@samccann would this work for the links? I'm applying the same color as in docs.ansible

**Review by samccann — APPROVED** [review]
LGTM and thanks!

**Comment by samccann** [comment]
@cristianonicolai - I noticed something odd at https://ansible.readthedocs.io/projects/dev-tools/. It looks like it's using the updated theme, but if you click on any of the top menu items, the page goes back to purple (the default material theme I think)?

https://ansible.readthedocs.io/projects/dev-tools/contributor-guide/ for example.  Should I open a separate issue for this or is it some transient problem that will 'fix itself' over time?

**Comment by cristianonicolai** [comment]
@samccann thanks for checking that, feel free to open a new issue, I'll take a look

**Pull request merged**
